# Generated by Django 4.0.2 on 2022-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilsManger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.IntegerField()),
                ('uploded_by', models.IntegerField()),
                ('uploded_at', models.DateTimeField()),
            ],
        ),
    ]
