# Generated by Django 4.0.2 on 2022-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MB52',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.IntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(null=True)),
                ('material', models.CharField(max_length=30, null=True)),
                ('division', models.CharField(max_length=20, null=True)),
                ('store', models.CharField(max_length=10, null=True)),
                ('store_level_deletion_indicator', models.CharField(max_length=15, null=True)),
                ('unit', models.CharField(max_length=5, null=True)),
                ('for_free_use', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=5, null=True)),
                ('value_free_use', models.FloatField(null=True)),
                ('transit_transfer', models.FloatField(null=True)),
                ('transit_transfer_value', models.FloatField(null=True)),
                ('in_quality_control', models.FloatField(null=True)),
                ('value_quality_control', models.FloatField(null=True)),
                ('non_free_stock', models.FloatField(null=True)),
                ('non_free_value', models.FloatField(null=True)),
                ('blocked', models.FloatField(null=True)),
                ('blocked_stock_value', models.FloatField(null=True)),
                ('returns', models.FloatField(null=True)),
                ('blocked_return_stock_value', models.FloatField(null=True)),
            ],
        ),
    ]
