# Generated by Django 4.0.2 on 2022-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SE16N_CEPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('profit_center', models.CharField(max_length=30, null=True)),
                ('valid_to', models.DateField(null=True)),
                ('controlling_area', models.CharField(max_length=30, null=True)),
                ('valid_from', models.DateField(null=True)),
                ('created_on', models.DateField(null=True)),
                ('created_by', models.CharField(max_length=30, null=True)),
                ('field_name_of_CO_PA_characteristic', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=30, null=True)),
                ('person_responsible_for_profit_center', models.CharField(max_length=30, null=True)),
                ('user_responsible', models.CharField(max_length=30, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('successor_profit_center', models.CharField(max_length=30, null=True)),
                ('country_key', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('name1', models.CharField(max_length=30, null=True)),
                ('name2', models.CharField(max_length=30, null=True)),
                ('name3', models.CharField(max_length=30, null=True)),
                ('name4', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('street', models.CharField(max_length=30, null=True)),
                ('po_box', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=30, null=True)),
                ('p_o_box_costal_code', models.CharField(max_length=30, null=True)),
                ('language_key', models.CharField(max_length=10, null=True)),
                ('telebox_number', models.CharField(max_length=30, null=True)),
                ('telephone1', models.CharField(max_length=30, null=True)),
                ('telephone2', models.CharField(max_length=30, null=True)),
                ('fax_number', models.CharField(max_length=30, null=True)),
                ('teletex_number', models.CharField(max_length=30, null=True)),
                ('telex_number', models.CharField(max_length=30, null=True)),
                ('data_line', models.CharField(max_length=30, null=True)),
                ('printer_name', models.CharField(max_length=30, null=True)),
                ('hierarchy_area', models.CharField(max_length=30, null=True)),
                ('company_code', models.CharField(max_length=30, null=True)),
                ('joint_venture', models.CharField(max_length=30, null=True)),
                ('recovery_indicator', models.CharField(max_length=30, null=True)),
                ('equity_type', models.CharField(max_length=30, null=True)),
                ('tax_jurisdiction', models.CharField(max_length=30, null=True)),
                ('region', models.CharField(max_length=30, null=True)),
                ('usage', models.CharField(max_length=30, null=True)),
                ('application', models.CharField(max_length=30, null=True)),
                ('procedure', models.CharField(max_length=30, null=True)),
                ('logical_system', models.CharField(max_length=30, null=True)),
                ('lock_indicator', models.CharField(max_length=30, null=True)),
                ('prctr_formula_planning_template', models.CharField(max_length=30, null=True)),
                ('segment', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('long_text', models.CharField(max_length=100, null=True)),
                ('profit_center_short_text_for_matchcode', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
