# Generated by Django 4.0.2 on 2022-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_se16n_cepc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SE16N_T001L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('plant', models.CharField(max_length=20, null=True)),
                ('storage_location', models.CharField(max_length=20, null=True)),
                ('descr_of_storage_loc', models.CharField(max_length=100, null=True)),
                ('store_level_deletion_indicator', models.CharField(max_length=20, null=True)),
                ('division', models.CharField(max_length=20, null=True)),
                ('neg_stocks_in_sloc', models.CharField(max_length=20, null=True)),
                ('freeze_book_inv_sLoc', models.FloatField(null=True)),
                ('sloc_MRP_indicator', models.CharField(max_length=20, null=True)),
                ('authorization_check', models.CharField(max_length=20, null=True)),
                ('stor_resource', models.CharField(max_length=20, null=True)),
                ('hu_reqmnt', models.CharField(max_length=20, null=True)),
                ('sales_organization', models.CharField(max_length=20, null=True)),
                ('distribution_channel', models.CharField(max_length=20, null=True)),
                ('shipping_point_receiving_pt', models.CharField(max_length=20, null=True)),
                ('vendor', models.CharField(max_length=20, null=True)),
                ('customer', models.CharField(max_length=20, null=True)),
                ('business_system_of_mes', models.CharField(max_length=20, null=True)),
                ('inventory_management_type', models.CharField(max_length=20, null=True)),
                ('license_number', models.CharField(max_length=20, null=True)),
                ('in_transit_assignment', models.CharField(max_length=20, null=True)),
                ('tank_assgn', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
