# Generated by Django 4.0.2 on 2022-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_se16n_t001l'),
    ]

    operations = [
        migrations.CreateModel(
            name='SE16N_T024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('purchasing_group', models.CharField(max_length=20, null=True)),
                ('description_p_group', models.CharField(max_length=20, null=True)),
                ('tel_no_purch_group', models.CharField(max_length=20, null=True)),
                ('output_device', models.CharField(max_length=20, null=True)),
                ('fax_number', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('extension', models.CharField(max_length=20, null=True)),
                ('e_mail_address', models.CharField(max_length=50, null=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
