# Generated by Django 4.0.2 on 2022-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_se16n_t024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZMM_CARNET_CDE_IS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('request_no', models.CharField(max_length=20, null=True)),
                ('plant', models.FloatField(null=True)),
                ('storage_location', models.CharField(max_length=20, null=True)),
                ('purchase_document', models.FloatField(null=True)),
                ('poste1', models.FloatField(null=True)),
                ('due_date', models.FloatField(null=True)),
                ('vendor', models.CharField(max_length=50, null=True)),
                ('vendor_name', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=50, null=True)),
                ('designation_add_material', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('transmission_info', models.DateField(null=True)),
                ('validated_by', models.CharField(max_length=50, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('quantity_to_receive', models.FloatField(null=True)),
                ('date_of_purchase', models.DateField(null=True)),
                ('desired_date', models.DateField(null=True)),
                ('original_delivery_date', models.DateField(null=True)),
                ('contractual_delivery_date', models.DateField(null=True)),
                ('validated_delivery_date', models.DateField(null=True)),
                ('confirmed_quantity', models.FloatField(null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('expected_stock_week_w', models.FloatField(null=True)),
                ('expected_stock_week_w_1', models.FloatField(null=True)),
                ('expected_stock_week_w_2', models.FloatField(null=True)),
                ('expected_stock_week_w_3', models.FloatField(null=True)),
                ('expected_stock_week_w_4', models.FloatField(null=True)),
                ('expected_stock_week_w_5', models.FloatField(null=True)),
                ('expected_stock_week_w_6', models.FloatField(null=True)),
                ('expected_stock_week_w_7', models.FloatField(null=True)),
                ('expected_stock_week_w_8', models.FloatField(null=True)),
                ('expected_stock_week_w_9', models.FloatField(null=True)),
                ('expected_stock_week_w_10', models.FloatField(null=True)),
                ('expected_stock_week_w_11', models.FloatField(null=True)),
                ('expected_stock_week_w_12', models.FloatField(null=True)),
                ('confirmation', models.CharField(max_length=10, null=True)),
                ('estimated_delivery_time', models.FloatField(null=True)),
                ('comment_vendor', models.CharField(max_length=500, null=True)),
                ('element_otp', models.CharField(max_length=10, null=True)),
                ('business_document', models.CharField(max_length=10, null=True)),
                ('poste2', models.FloatField(null=True)),
                ('need_number', models.FloatField(null=True)),
                ('net_price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('price_basis', models.FloatField(null=True)),
                ('price_unit', models.CharField(max_length=10, null=True)),
                ('net_order_value', models.FloatField(null=True)),
                ('purchasing_document_type', models.CharField(max_length=10, null=True)),
                ('exception_message_number', models.FloatField(null=True)),
                ('exception_message', models.CharField(max_length=50, null=True)),
                ('purchasing_group', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
