# Generated by Django 4.0.2 on 2022-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_zmm_carnet_cde_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='due_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='estimated_delivery_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='exception_message_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='plant',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='poste1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='poste2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='price_basis',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='purchase_document',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
