# Generated by Django 4.0.2 on 2022-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_zmm_carnet_cde_is_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='plant',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='poste1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='purchase_document',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='request_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='storage_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='uploaded_by',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
