# Generated by Django 4.0.2 on 2022-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_zmm_carnet_cde_is_plant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZRPFLG13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.FloatField(null=True)),
                ('plant', models.FloatField(null=True)),
                ('ctr_pft', models.CharField(max_length=10, null=True)),
                ('administrator', models.CharField(max_length=10, null=True)),
                ('tech_desc', models.CharField(max_length=10, null=True)),
                ('customer_grp', models.CharField(max_length=10, null=True)),
                ('article_reference', models.CharField(max_length=10, null=True)),
                ('ty', models.CharField(max_length=10, null=True)),
                ('st', models.FloatField(null=True)),
                ('gv', models.CharField(max_length=10, null=True)),
                ('Needs', models.FloatField(null=True)),
                ('Stock', models.FloatField(null=True)),
                ('Consign_stock', models.FloatField(null=True)),
                ('lot_qm', models.FloatField(null=True)),
                ('of', models.FloatField(null=True)),
                ('cde', models.FloatField(null=True)),
                ('op', models.FloatField(null=True)),
                ('da', models.FloatField(null=True)),
                ('Key', models.CharField(max_length=10, null=True)),
                ('Fixed_lot', models.FloatField(null=True)),
                ('Security', models.FloatField(null=True)),
                ('surpluses', models.FloatField(null=True)),
                ('Valuation', models.FloatField(null=True)),
                ('time_limit_of_secu', models.FloatField(null=True)),
                ('pmp_ps', models.FloatField(null=True)),
                ('abc', models.CharField(max_length=10, null=True)),
                ('Mini_lot', models.FloatField(null=True)),
                ('rounds', models.FloatField(null=True)),
                ('tps_recept', models.FloatField(null=True)),
                ('maxi_lot', models.FloatField(null=True)),
                ('Storage_loc', models.FloatField(null=True)),
                ('desc_material', models.CharField(max_length=20, null=True)),
                ('curency', models.CharField(max_length=10, null=True)),
                ('material_type', models.CharField(max_length=10, null=True)),
                ('appro_spe', models.CharField(max_length=10, null=True)),
                ('vrac', models.CharField(max_length=10, null=True)),
                ('planif_type', models.CharField(max_length=10, null=True)),
                ('vendor1', models.CharField(max_length=10, null=True)),
                ('desc_vendor1', models.CharField(max_length=20, null=True)),
                ('vendor2', models.CharField(max_length=10, null=True)),
                ('desc_vendor2', models.CharField(max_length=20, null=True)),
                ('stock_in_transit', models.FloatField(null=True)),
                ('required_quantity_1000', models.FloatField(null=True)),
                ('required_quantity_1010', models.FloatField(null=True)),
                ('required_quantity_1900', models.FloatField(null=True)),
                ('required_quantity_3000', models.FloatField(null=True)),
                ('required_quantity_3100', models.FloatField(null=True)),
                ('required_quantity_4000', models.FloatField(null=True)),
                ('required_quantity_5000', models.FloatField(null=True)),
                ('vmi_stock', models.FloatField(null=True)),
                ('item_order', models.FloatField(null=True)),
                ('planif_device', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
    ]
