# Generated by Django 4.0.2 on 2022-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_zrpflg13_alter_zmm_carnet_cde_is_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='zrpflg13',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zrpflg13',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
    ]
