# Generated by Django 4.0.2 on 2022-02-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_zrpflg13_uploaded_at_zrpflg13_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Storage_loc',
            new_name='storage_loc',
        ),
    ]
