# Generated by Django 4.0.2 on 2022-02-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_storage_loc_zrpflg13_storage_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='article_reference',
            new_name='material',
        ),
    ]
