# Generated by Django 4.0.2 on 2022-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_article_reference_zrpflg13_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='zrpflg13',
            name='decoupling_point',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
