# Generated by Django 4.0.2 on 2022-02-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_zrpflg13_decoupling_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Consign_stock',
            new_name='consign_stock',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Fixed_lot',
            new_name='fixed_lot',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Mini_lot',
            new_name='mini_lot',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Needs',
            new_name='needs',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Security',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='zrpflg13',
            old_name='Valuation',
            new_name='valuation',
        ),
    ]
