# Generated by Django 4.0.2 on 2022-02-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_consign_stock_zrpflg13_consign_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='confirmation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='element_otp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zrpflg13',
            name='needs',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
