# Generated by Django 4.0.2 on 2022-02-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_zmm_carnet_cde_is_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='need_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
