# Generated by Django 4.0.2 on 2022-02-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_zmm_carnet_cde_is_need_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zrpflg13',
            name='desc_vendor1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
