# Generated by Django 4.0.2 on 2022-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_zrpflg13_desc_vendor1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zrpflg13',
            name='desc_material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
