# Generated by Django 4.0.2 on 2022-02-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_zrpflg13_desc_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField()),
                ('deleted_by', models.IntegerField()),
                ('deleted_on', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('plant', models.CharField(max_length=30, null=True)),
                ('program', models.CharField(max_length=30, null=True)),
                ('supplier', models.CharField(max_length=30, null=True)),
                ('part_number', models.CharField(max_length=30, null=True)),
                ('create', models.CharField(max_length=30, null=True)),
                ('type_of_alert', models.CharField(max_length=30, null=True)),
                ('requested_date', models.DateField()),
                ('needed_quantity', models.FloatField()),
                ('production_comments', models.TextField(null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('procurement_comments', models.TextField()),
                ('closing_date', models.DateField()),
                ('duration_of_the_event', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
