# Generated by Django 4.0.2 on 2022-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='closing_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='core',
            name='requested_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='se16n_cepc',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='se16n_cepc',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='se16n_cepc',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='contractual_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='date_of_purchase',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='desired_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='original_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='transmission_info',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='validated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
