# Generated by Django 4.0.2 on 2022-03-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0002_alter_core_closing_date_alter_core_requested_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corehistory',
            old_name='id_core',
            new_name='core',
        ),
        migrations.AlterField(
            model_name='corehistory',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
