# Generated by Django 4.0.2 on 2022-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0004_rename_create_core_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='closing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
